config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/terms', to: 'static_pages#terms'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:index, :new, :show, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  validates   :user_id, presence: true
  validates   :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user
  before_action :set_variables

  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:id])
    like.destroy
  end

  private
    def set_variables
      @micropost = Micropost.find(params[:id])
      @id_name = "#like-#{@micropost.id}"
      @id_heart = "#heart-#{@micropost.id}"
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if Like.find_by(user_id: current_user.id, post_id: micropost.id) %>
  <%= link_to(like_path(id: micropost.id), method: :delete, remote: true) do %>
    <span id="heart-<%= micropost.id %>" class="fa fa-heart like-btn-on"></span>
    いいね！
  <% end %>
<% else %>
  <%= link_to(likes_path(id: micropost.id), method: :post, remote: true) do %>
    <span id="heart-<%= micropost.id %>" class="far fa-heart"></span>
    いいね！
  <% end %>
<% end %>
<%= Like.where(post_id: micropost.id).size %> 件

app/views/likes/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", micropost: @micropost  )) %>');
$("<%= @id_heart %>").removeClass('far');
$("<%= @id_heart %>").addClass('fa like-btn-on');

app/views/likes/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", micropost: @micropost  )) %>');
$("<%= @id_heart %>").removeClass('fa like-btn-on');
$("<%= @id_heart %>").addClass('far');