config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/terms', to: 'static_pages#terms'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:index, :new, :show, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :picture, presence: true
  validate  :picture_size

  has_many :likes
  has_many :comments, dependent: :destroy
  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @microposts = Micropost.includes(:user).all
  end

  def show
    @micropost = Micropost.find_by(id: params[:id])
    @comments = Comment.where(micropost_id: params[:id])
    @comment = Comment.new
  end

  def new
    @micropost = current_user.microposts.build if logged_in?
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      #画像のみ投稿の場合 params.fetch(:micropost, {}).permit(:picture)
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="col-md-4">
  <div class="micropost_box">
    <%= link_to gravatar_for(micropost.user, size: 30), micropost.user, id: "gravatar-#{micropost.user.id}" %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <div class="clear"></div>
    <span class="content">
      <%= link_to(micropost_path(micropost.id), id: "picture-link-#{micropost.id}", remote: true) do %>
        <%= image_tag micropost.picture.url, id: "picture-#{micropost.id}" unless micropost.picture.blank? %>
      <% end %>
      <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    </span>
    <span class="font-btn" id="like-<%= micropost.id %>">
      <%= render "likes/like", micropost: micropost %>
    </span>
    <%= link_to(micropost_path(micropost.id), remote: true) do %>
      <i class="font-btn far fa-comment-dots"></i>
    <% end %>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
      <% if current_user?(micropost.user) %>
        <%= link_to "delete", micropost, method: :delete,
                          data: { confirm: "You sure?" } %>
      <% end %>
    </span>
  </div>
</li>

app/views/microposts/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="col-md-6">
      <%= image_tag @micropost.picture.url, class: "image_center" %>
    </div>
    <div class="col-md-6">
      <p><%= @micropost.content if @micropost.content? %></p>
      <ul class="comment_ul">
        <% @comments.each do |comment| %>
          <li class="comment_li">
            <%= User.find_by(id: comment.user_id).name %>：<%= comment.content %>
            <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: "You sure?" } %>
          </li>
        <% end %>
      </ul>
      <%= render "comments/comment_form", micropost: @micropost %>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/microposts/index.html.erb
<% provide(:title, "検索結果") %>

<div class="row">
  <div>
    <% if @results.present? %>
      <ol class="microposts">
        <%= render @results %>
      </ol>
      <div class="clear"></div>
      <div class="text-center">
        <%= will_paginate @results %>
      </div>
    <% end %>

    <% if @results.nil? %>
      <% if @microposts.any? %>
        <h3>Microposts (<%= @microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <div class="clear"></div>
        <div class="text-center">
          <%= will_paginate @microposts %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/microposts/new.html.erb
<% provide(:title, "投稿") %>
<h1>投稿</h1>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
</div>

app/views/microposts/show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="col-md-6">
      <%= image_tag @micropost.picture.url, class: "image_center" %>
    </div>
    <div class="col-md-6">
      <p><%= @micropost.content if @micropost.content? %></p>
      <ul class="comment_ul">
        <% @comments.each do |comment| %>
        <li class="comment_li">
          <%= User.find_by(id: comment.user_id).name %>：<%= comment.content %>
          <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: "You sure?" } %>
        </li>
        <% end %>
      </ul>
      <%= render "comments/comment_form", micropost: @micropost %>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/microposts/show.js.erb
$("#user-modal").html("<%= escape_javascript(render 'show') %>")
$("#user-modal").modal("show")